## 数据源配置 主数据源
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        #之前是 driverClassName现改成driver-class-name
    application:
        name:test-thymeleaf
    thymeleaf:
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
    #关闭thymeleaf的缓存。
mybatis:
    #配置Mapper的扫描路径  mybatis注解扫描
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.model
    table:
        auto: update
    model:
        pack: com.example.demo.model
    database:
        type: mysql

mybatis-plus:
#    mapper-locations: classpath:mapper/**/*.xml
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.model
    global-config:
        refresh: true
        #刷新mapper 调试神器
        db-config:
            #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
            id-type: auto
            #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
            field-strategy: NOT_EMPTY
            #驼峰下划线转换
            column-underline: true
            #数据库大写下划线转换
            #capital-mode: true
            #逻辑删除配置
            logic-delete-value: 1
            logic-not-delete-value: 0
            db-type: mysql
            #自定义SQL注入器
        configuration:
            map-underscore-to-camel-case: true
            cache-enabled: false
#jsp页面映射  springboot不支持jsp页面，需要导入jar包。
#mvc:
#    view:
      #  prefix:WEB-INF/jsp/
#        prefix:/WEB-INF/jsp/
#        suffix:.jsp
        #  http请求映射
    #static-path-pattern:/**
    #Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
    # in 'reader', line 43, column 5:
    #        static-path-pattern:/**

#    静态资源
#resources:
#   static-locations:classpath:*/js/,classpath:*/img/