server:
  port: 8080
## 数据源配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.model
mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.example.demo.model
    global-config:
        refresh: true
        #刷新mapper 调试神器
        db-config:
            #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
            id-type: auto
            #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
            field-strategy: NOT_EMPTY
            #驼峰下划线转换
            column-underline: true
            #数据库大写下划线转换
            #capital-mode: true
            #逻辑删除配置
            logic-delete-value: 1
            logic-not-delete-value: 0
            db-type: mysql
            #自定义SQL注入器
        configuration:
            map-underscore-to-camel-case: true
            cache-enabled: false
